apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kmesh
  labels:
    app: kmesh
rules:
- apiGroups: [""]
  resources: ["pods","services","namespaces"]
  verbs: ["get", "update", "patch"]
