deploy:
  kmesh:
    env:
      bpfLogSize: "12800"
      xdsAddress: istiod.istio-system.svc:15012
    image:
      repository: ghcr.io/kmesh-net/kmesh
      tag: latest
    imagePullPolicy: IfNotPresent
    containers:
      kmeshDaemonArgs: "--mode=workload --enable-bypass=false --enable-bpf-log=true"
    resources:
      limits:
        cpu: "1"
        memory: 800Mi
kubernetesClusterDomain: cluster.local
