deploy:
  kmesh:
    env:
      bpfLogSize: "12800"
      meshController: istiod.istio-system.svc:15012
    image:
      repository: ghcr.io/kmesh-net/kmesh
      tag: 0.2.0
    imagePullPolicy: IfNotPresent
    containers:
      kmeshDaemonArgs: "-enable-kmesh -enable-ads=true"
    resources:
      limits:
        cpu: "1"
        memory: 800Mi
kubernetesClusterDomain: cluster.local
